### ISSUE TITLE
Start arftracksat

### ISSUE THREAD

**Issue by graememilne** [arf20/arftracksat#25]
After sorting out the make errors, which was i had to install libglm-dev it completed the build/make without errors.
Now the daft question is how do you get the software to run ???

**Comment by arf20** [comment]
Yeah I forgot to update README. Done now at [39fe2ed](https://github.com/arf20/arftracksat/commit/39fe2edb46c7a97da4fb0ff06f62e9bdfa58b74a)

Your questions are now answered there. Please ask if you have more, and thank you for the interest in this little project.
