### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by mabster314** [arf20/arftracksat#40]
Hello,

No license is provided for the program, can you please specify one or clarify whether it is acceptable for distribution/derivative works?

**Comment by arf20** [comment]
Oh, I forgot about licensing this.
You are totally free to distribute and fork this project, kind of like MIT.
But I will license this with GPL at some point.
Its still a WIP, but the development has been very slow lately because I don't really know modern OpenGL.

**Comment by mabster314** [comment]
Thank you very much!

**Comment by arf20** [comment]
Np, happy to see people interested in this project!
I should come back to it lol. I was trying to port it to OpenGL 3.3.
